rotis_course_maker:
    resource: "@RotisCourseMakerBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern: /login
    defaults: { _controller: RotisCourseMakerBundle:Security:login }
login_check:
    pattern: /login_check
logout:
    pattern:   /logout
register:
    pattern: /register
    defaults: { _controller: RotisCourseMakerBundle:Equipe:register }
create:
    pattern: /create
    defaults: { _controller: RotisCourseMakerBundle:Equipe:create }
contact:
    pattern: /contact
    defaults: { _controller: RotisCourseMakerBundle:CourseMaker:contact }
accueil:
    pattern: /accueil
    defaults: { _controller: RotisCourseMakerBundle:CourseMaker:accueil }
account:
    pattern: /account
    defaults: { _controller: RotisCourseMakerBundle:Security:account }
infos_pratiques:
    pattern: /infos_pratiques
    defaults: { _controller: RotisCourseMakerBundle:CourseMaker:infos }

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
