Rotis\CourseMakerBundle\Entity\Equipe:
  type: entity
  table: null
  repositoryClass: Rotis\CourseMakerBundle\Entity\EquipeRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    password:
      type: string
      length: 125
    username:
      type: string
      length: 25
      unique: true
    isActive:
      type: boolean
    salt:
      type: string
      length: 32
    valide:
      type: boolean
  manyToOne:
    course:
      targetEntity: Course
      inversedBy: equipes
    categorie:
      targetEntity: Categorie
      inversedBy: equipes 
  oneToMany:
    joueurs:
      targetEntity: Joueur
      mappedBy: equipe
  lifecycleCallbacks: {  }
