login:
    pattern: /login
    defaults: { _controller: RotisCourseMakerBundle:Security:login }
admin_home:
    pattern: /admin
    defaults: { _controller: RotisCourseMakerBundle:CourseMaker:admin }
admin_control:
    pattern: /admin/{name}
    defaults: { _controller: RotisCourseMakerBundle:Equipe:liste }
login_check:
    pattern: /login_check
logout:
    pattern:  /logout
register:
    pattern: /register
    defaults: { _controller: RotisCourseMakerBundle:Equipe:register }
create:
    pattern: /create
    defaults: { _controller: RotisCourseMakerBundle:Equipe:create }
edit:
    pattern: /edit/{name}
    defaults: { _controller: RotisCourseMakerBundle:Equipe:edit }
contact:
    pattern: /contact
    defaults: { _controller: RotisCourseMakerBundle:CourseMaker:contact }
accueil:
    pattern: /accueil
    defaults: { _controller: RotisCourseMakerBundle:CourseMaker:accueil }
account:
    pattern: /equipe/{name}
    defaults: { _controller: RotisCourseMakerBundle:Equipe:edit_equipe }
infos_pratiques:
    pattern: /infos_pratiques
    defaults: { _controller: RotisCourseMakerBundle:CourseMaker:infos }